version: "3.3"
services:

  daq:
    image: gasiepgodoy/moleculer:megaind-rpi-v7
    container_name: megaind-rpi-v8
    env_file:
      - .env
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1